export type Lang = "en" | "vi";

export const profile = {
  name: "Doan Vo Nguyen",
  nameVi: "Đoàn Võ Nguyên",
  initials: "DN",
  role: "Fullstack Developer",
  email: "wwwdoanvonguyen@gmail.com",
  phoneDisplay: "085 721 1086",
  phoneHref: "tel:+84857211086",
  location: "Quy Nhon, Gia Lai, Vietnam",
  locationVi: "Quy Nhơn, Gia Lai, Việt Nam",
  address: "138 Can Vuong, Quy Nhon, Gia Lai",
  addressVi: "138 Cản Vương, Quy Nhơn, Gia Lai",
  github: "https://github.com/Doan-Vo-Nguyen",
  githubHandle: "Doan-Vo-Nguyen",
  avatar: "https://avatars.githubusercontent.com/u/83484931?v=4",
  resume: "/Doan-Vo-Nguyen-Resume.pdf",
};

export const copy = {
  en: {
    nav: {
      work: "Work",
      about: "About",
      experience: "Experience",
      certificates: "Certs",
      contact: "Contact",
      resume: "Resume",
      menu: "Menu",
      close: "Close",
    },
    hero: {
      kicker: "Fullstack Developer",
      line1: "Doan",
      line2: "Vo",
      line3: "Nguyen",
      statement:
        "I build web systems that feel calm, clear, and fast — from authentication platforms to education products and LLM-powered tools.",
      location: "Based in Quy Nhon",
      now: "Currently at HP Edtech Center",
      cta: "See selected work",
      scroll: "Scroll",
      rotating: ["Systems", "Platforms", "Interfaces", "AI tools"],
      available: "Open to opportunities",
    },
    about: {
      index: "01",
      label: "About",
      title: "Engineer, teacher, and builder of digital products.",
      p1: "I am a newly graduated Information Technology engineer with two years of professional experience at NCC Plus Vietnam, now working as a Teacher and Software Developer at HP Edtech Center.",
      p2: "My background sits at the intersection of backend systems, databases, and fullstack web applications. At NCC Plus I contributed to Speedydd — a document authentication system used between the European Union and partners outside the EU. I communicate in English, work well with teammates, and keep learning in public.",
      stats: [
        { value: "2", unit: "yrs", label: "Professional experience" },
        { value: "3.23", unit: "/4.00", label: "GPA · Very Good" },
        { value: "8", unit: "ppl", label: "Speedydd team size" },
        { value: "14", unit: "+", label: "Public repositories" },
      ],
      capabilities: [
        "Backend APIs",
        "Fullstack web",
        "Auth & payments",
        "LLM integration",
        "Education products",
        "Realtime features",
      ],
    },
    experience: {
      index: "02",
      label: "Experience",
      title: "Where I have been building.",
      items: [
        {
          company: "HP Edtech Center",
          role: "Teacher & Software Developer",
          period: "08.2026 — Present",
          location: "Quy Nhon",
          bullets: [
            "Teach and develop Computer Science and Information Technology programs.",
            "Design, build, and maintain educational web platforms for teaching and student engagement.",
            "Ship AI-powered features and integrate Large Language Models into applications.",
            "Create internal tools, learning materials, and technical support for academic operations.",
          ],
        },
        {
          company: "NCC Plus Vietnam",
          role: "Node.js Intern",
          period: "07.2024 — 04.2025",
          location: "Vietnam",
          bullets: [
            "Worked on Speedydd, a document authentication platform for EU businesses and joint ventures.",
            "Collaborated in an 8-person team with Next.js, Express, and MongoDB.",
            "Implemented Google authentication for secure system access.",
            "Built monthly payment for individual participants and the My Job module for business administrators.",
          ],
        },
      ],
    },
    work: {
      index: "03",
      label: "Selected work",
      title: "Projects with intent.",
      view: "View",
      live: "Live",
      code: "Code",
      items: [
        {
          title: "HP Edtech Center",
          role: "Fullstack Developer",
          year: "2026",
          tags: ["React", "Vite", "Express", "MySQL", "MongoDB"],
          summary:
            "Website and learning platform for HP Edtech Center. Frontend with React + Vite, backend with Node.js/Express, and data on MySQL plus MongoDB — courses, student engagement, and classroom tools.",
          href: null,
          live: null,
        },
        {
          title: "Speedydd",
          role: "Backend Developer",
          year: "2024–25",
          tags: ["Next.js", "Express", "MongoDB", "Google Auth"],
          summary:
            "Document authentication system used by European businesses and EU joint ventures. Google login, monthly payments per participant, and a My Job workspace for administrators. Team of 8.",
          href: null,
          live: null,
        },
        {
          title: "Realtime Chat",
          role: "Fullstack Developer",
          year: "2024",
          tags: ["React", "Express", "Vite", "ChatEngine"],
          summary:
            "Realtime messaging product for text and lightweight file exchange. Focused on interface, API integration, and live communication.",
          href: "https://github.com/Doan-Vo-Nguyen/RealTimeChat",
          live: null,
        },
        {
          title: "Crowd Sale Green Fund",
          role: "Fullstack Developer",
          year: "2024",
          tags: ["JavaScript", "Web", "Vercel"],
          summary:
            "Crowdsale experience for a green-fund initiative. Public web app deployed on Vercel.",
          href: "https://github.com/Doan-Vo-Nguyen/crowd-sale-greend-fund",
          live: "https://crowd-sale-greend-fund.vercel.app",
        },
        {
          title: "Smart Car Parking",
          role: "Fullstack Developer",
          year: "2024–25",
          tags: ["PHP", "Systems"],
          summary:
            "Parking management system covering slots, flow, and operational views for a smarter lot.",
          href: "https://github.com/Doan-Vo-Nguyen/Smart_Car_Parking",
          live: null,
        },
      ],
    },
    skills: {
      index: "04",
      label: "Stack",
      title: "Tools I reach for.",
      groups: [
        {
          name: "Programming",
          items: ["JavaScript", "Node.js", "Express.js", "React", "Next.js"],
        },
        {
          name: "Data & APIs",
          items: ["MongoDB", "MySQL", "REST APIs", "Axios"],
        },
        {
          name: "Platform",
          items: ["Git", "Docker", "Vite", "Google Auth", "LLM integration"],
        },
        {
          name: "Also used",
          items: ["Python", "PHP", "C#"],
        },
      ],
      marquee: [
        "JavaScript",
        "Node.js",
        "Express",
        "React",
        "Next.js",
        "MongoDB",
        "MySQL",
        "REST APIs",
        "Git",
        "Docker",
        "Vite",
        "Google Auth",
        "LLM",
        "Python",
        "PHP",
        "C#",
      ],
      language: "English — listening, speaking, reading, writing",
    },
    studio: {
      index: "05",
      label: "Studio",
      title: "Education, activities, interests.",
      education: {
        kicker: "Education",
        school: "Quy Nhon University",
        period: "2021 — 2025",
        degree: "Information Technology · Information System",
        note: "Very Good · GPA 3.23 / 4.00",
      },
      activity: {
        kicker: "Activities",
        org: "Youth Assault IT Department",
        period: "2021 — 2023",
        role: "Communications Board",
        note: "Photography, posters, cards, banners, and video. Volunteer work including Green Summer and beach cleaning.",
      },
      interests: {
        kicker: "Interests",
        items: [
          "New technology trends",
          "Learning English",
          "Music",
          "Reading",
        ],
      },
    },
    certificates: {
      index: "06",
      label: "Certificates",
      title: "Google for Education.",
      issuer: "Google",
      view: "View certificate",
      items: [
        {
          title: "Google Certified Educator Level 1",
          period: "Aug 2026 — Aug 2029",
          note: "Foundational certification for teaching and learning with Google tools.",
          href: "/Google_Educator_Certificate_level_1.pdf",
          image: "/certificates/google-educator-level-1.png",
        },
        {
          title: "Google Certified Educator Level 2",
          period: "Sep 2026 — Sep 2029",
          note: "Advanced certification for transforming instruction with Google tools.",
          href: "/Google_Educator_Certificate_level_2.pdf",
          image: "/certificates/google-educator-level-2.png",
        },
        {
          title: "Gemini Certified Educator",
          period: "Sep 2026 — Sep 2029",
          note: "Certification for using Google AI tools in planning, teaching, and student work.",
          href: "/Google_Educator_AI_Certificate.pdf",
          image: "/certificates/google-educator-ai.png",
        },
      ],
    },
    contact: {
      index: "07",
      label: "Contact",
      title: "Let’s build something precise.",
      body: "Open to collaborations, teaching-tech products, and fullstack roles. Say hello — I read every message.",
      emailLabel: "Email",
      phoneLabel: "Phone",
      githubLabel: "GitHub",
      locationLabel: "Location",
      copy: "Copy",
      copied: "Copied",
      resume: "Download resume",
    },
    footer: {
      rights: "All rights reserved.",
      local: "Local time",
      built: "Designed & developed by Doan Vo Nguyen",
    },
  },
  vi: {
    nav: {
      work: "Dự án",
      about: "Giới thiệu",
      experience: "Kinh nghiệm",
      certificates: "Chứng chỉ",
      contact: "Liên hệ",
      resume: "CV",
      menu: "Menu",
      close: "Đóng",
    },
    hero: {
      kicker: "Lập trình viên Fullstack",
      line1: "Doan",
      line2: "Vo",
      line3: "Nguyen",
      statement:
        "Tôi xây dựng hệ thống web điềm tĩnh, rõ ràng và nhanh — từ nền tảng xác thực tài liệu đến sản phẩm giáo dục và công cụ tích hợp LLM.",
      location: "Sống và làm việc tại Quy Nhơn",
      now: "Hiện tại: HP Edtech Center",
      cta: "Xem dự án tiêu biểu",
      scroll: "Cuộn",
      rotating: ["Hệ thống", "Nền tảng", "Giao diện", "Công cụ AI"],
      available: "Sẵn sàng hợp tác",
    },
    about: {
      index: "01",
      label: "Giới thiệu",
      title: "Kỹ sư, giáo viên, và người làm sản phẩm số.",
      p1: "Tôi là kỹ sư Công nghệ Thông tin mới tốt nghiệp, hai năm kinh nghiệm tại NCC Plus Vietnam, hiện giảng dạy và phát triển phần mềm tại HP Edtech Center.",
      p2: "Nền tảng của tôi nằm ở giao điểm backend, cơ sở dữ liệu và ứng dụng web fullstack. Tại NCC Plus tôi tham gia Speedydd — hệ thống xác thực tài liệu giữa Liên minh Châu Âu và đối tác ngoài EU. Tôi giao tiếp bằng tiếng Anh, làm việc nhóm tốt, và luôn chủ động học hỏi, chia sẻ.",
      stats: [
        { value: "2", unit: "năm", label: "Kinh nghiệm chuyên môn" },
        { value: "3.23", unit: "/4.00", label: "GPA · Giỏi" },
        { value: "8", unit: "người", label: "Quy mô team Speedydd" },
        { value: "14", unit: "+", label: "Kho lưu trữ công khai" },
      ],
      capabilities: [
        "Backend API",
        "Web fullstack",
        "Auth & thanh toán",
        "Tích hợp LLM",
        "Sản phẩm giáo dục",
        "Tính năng realtime",
      ],
    },
    experience: {
      index: "02",
      label: "Kinh nghiệm",
      title: "Những nơi tôi đã xây.",
      items: [
        {
          company: "HP Edtech Center",
          role: "Giảng viên & Software Developer",
          period: "08.2026 — Hiện tại",
          location: "Quy Nhơn",
          bullets: [
            "Giảng dạy và phát triển chương trình Khoa học Máy tính và Công nghệ Thông tin.",
            "Thiết kế, xây dựng và vận hành nền tảng web phục vụ dạy học và tương tác học viên.",
            "Phát triển tính năng AI và tích hợp Large Language Models vào ứng dụng.",
            "Xây dựng công cụ nội bộ, học liệu và hỗ trợ kỹ thuật cho vận hành giáo dục.",
          ],
        },
        {
          company: "NCC Plus Vietnam",
          role: "Thực tập Node.js",
          period: "07.2024 — 04.2025",
          location: "Việt Nam",
          bullets: [
            "Tham gia Speedydd — nền tảng xác thực tài liệu cho doanh nghiệp và liên doanh EU.",
            "Làm việc trong team 8 người với Next.js, Express và MongoDB.",
            "Triển khai đăng nhập Google để truy cập hệ thống an toàn.",
            "Xây dựng thanh toán theo tháng cho từng cá nhân và chức năng My Job cho quản trị doanh nghiệp.",
          ],
        },
      ],
    },
    work: {
      index: "03",
      label: "Dự án tiêu biểu",
      title: "Sản phẩm có chủ đích.",
      view: "Xem",
      live: "Live",
      code: "Code",
      items: [
        {
          title: "HP Edtech Center",
          role: "Fullstack Developer",
          year: "2026",
          tags: ["React", "Vite", "Express", "MySQL", "MongoDB"],
          summary:
            "Website và nền tảng học tập cho HP Edtech Center. Frontend React + Vite, backend Node.js/Express, dữ liệu MySQL và MongoDB — khóa học, tương tác học viên, và công cụ lớp học.",
          href: null,
          live: null,
        },
        {
          title: "Speedydd",
          role: "Backend Developer",
          year: "2024–25",
          tags: ["Next.js", "Express", "MongoDB", "Google Auth"],
          summary:
            "Hệ thống xác thực tài liệu cho doanh nghiệp Châu Âu và liên doanh EU. Đăng nhập Google, thanh toán theo tháng, workspace My Job cho quản trị. Team 8 người.",
          href: null,
          live: null,
        },
        {
          title: "Realtime Chat",
          role: "Fullstack Developer",
          year: "2024",
          tags: ["React", "Express", "Vite", "ChatEngine"],
          summary:
            "Sản phẩm nhắn tin realtime, gửi chữ và tệp đơn giản. Tập trung giao diện, tích hợp API và giao tiếp trực tiếp.",
          href: "https://github.com/Doan-Vo-Nguyen/RealTimeChat",
          live: null,
        },
        {
          title: "Crowd Sale Green Fund",
          role: "Fullstack Developer",
          year: "2024",
          tags: ["JavaScript", "Web", "Vercel"],
          summary:
            "Trải nghiệm crowdsale cho quỹ xanh. Ứng dụng web công khai triển khai trên Vercel.",
          href: "https://github.com/Doan-Vo-Nguyen/crowd-sale-greend-fund",
          live: "https://crowd-sale-greend-fund.vercel.app",
        },
        {
          title: "Smart Car Parking",
          role: "Fullstack Developer",
          year: "2024–25",
          tags: ["PHP", "Hệ thống"],
          summary:
            "Hệ thống quản lý bãi đỗ — vị trí, luồng xe, và góc nhìn vận hành cho một bãi đỗ thông minh hơn.",
          href: "https://github.com/Doan-Vo-Nguyen/Smart_Car_Parking",
          live: null,
        },
      ],
    },
    skills: {
      index: "04",
      label: "Công nghệ",
      title: "Công cụ tôi dùng.",
      groups: [
        {
          name: "Lập trình",
          items: ["JavaScript", "Node.js", "Express.js", "React", "Next.js"],
        },
        {
          name: "Dữ liệu & API",
          items: ["MongoDB", "MySQL", "REST APIs", "Axios"],
        },
        {
          name: "Nền tảng",
          items: ["Git", "Docker", "Vite", "Google Auth", "LLM integration"],
        },
        {
          name: "Cũng đã dùng",
          items: ["Python", "PHP", "C#"],
        },
      ],
      marquee: [
        "JavaScript",
        "Node.js",
        "Express",
        "React",
        "Next.js",
        "MongoDB",
        "MySQL",
        "REST APIs",
        "Git",
        "Docker",
        "Vite",
        "Google Auth",
        "LLM",
        "Python",
        "PHP",
        "C#",
      ],
      language: "Tiếng Anh — nghe, nói, đọc, viết",
    },
    studio: {
      index: "05",
      label: "Hành trình",
      title: "Học vấn, hoạt động, sở thích.",
      education: {
        kicker: "Học vấn",
        school: "Đại học Quy Nhơn",
        period: "2021 — 2025",
        degree: "Công nghệ Thông tin · Hệ thống thông tin",
        note: "Giỏi · GPA 3.23 / 4.00",
      },
      activity: {
        kicker: "Hoạt động",
        org: "Thanh niên xung kích Khoa CNTT",
        period: "2021 — 2023",
        role: "Ban Truyền thông",
        note: "Thiết kế, nhiếp ảnh, poster, thiệp, banner và dựng video. Tình nguyện Mùa hè xanh, dọn biển.",
      },
      interests: {
        kicker: "Sở thích",
        items: [
          "Xu hướng công nghệ",
          "Học tiếng Anh",
          "Nghe nhạc",
          "Đọc sách",
        ],
      },
    },
    certificates: {
      index: "06",
      label: "Chứng chỉ",
      title: "Google for Education.",
      issuer: "Google",
      view: "Xem chứng chỉ",
      items: [
        {
          title: "Google Certified Educator Level 1",
          period: "08.2026 — 08.2029",
          note: "Chứng chỉ nền tảng về dạy và học với công cụ Google.",
          href: "/Google_Educator_Certificate_level_1.pdf",
          image: "/certificates/google-educator-level-1.png",
        },
        {
          title: "Google Certified Educator Level 2",
          period: "09.2026 — 09.2029",
          note: "Chứng chỉ nâng cao về đổi mới giảng dạy với công cụ Google.",
          href: "/Google_Educator_Certificate_level_2.pdf",
          image: "/certificates/google-educator-level-2.png",
        },
        {
          title: "Gemini Certified Educator",
          period: "09.2026 — 09.2029",
          note: "Chứng chỉ sử dụng công cụ AI của Google trong soạn giảng, dạy học và hỗ trợ học viên.",
          href: "/Google_Educator_AI_Certificate.pdf",
          image: "/certificates/google-educator-ai.png",
        },
      ],
    },
    contact: {
      index: "07",
      label: "Liên hệ",
      title: "Cùng làm một thứ thật chỉn chu.",
      body: "Mở cho hợp tác, sản phẩm giáo dục-công nghệ, và vai trò fullstack. Cứ viết — tôi đọc mọi tin.",
      emailLabel: "Email",
      phoneLabel: "Điện thoại",
      githubLabel: "GitHub",
      locationLabel: "Địa điểm",
      copy: "Sao chép",
      copied: "Đã chép",
      resume: "Tải CV",
    },
    footer: {
      rights: "Mọi quyền được bảo lưu.",
      local: "Giờ địa phương",
      built: "Thiết kế & phát triển bởi Đoàn Võ Nguyên",
    },
  },
} as const;

export type Dictionary = (typeof copy)[Lang];
